# Nombre del microservicio
spring.application.name=ms_EurekaServer

# Puerto para Eureka
server.port=8761

# Que no se registre a sí mismo ni busque otros servidores
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
